openapi: 3.0.0
info:
  title: Dokaai Multi Service Application
  description: ''
  version: 1.0.0
tags:
- name: Member
  description: ''
- name: OPM Service
  description: ''
paths:
  '{{members-module}}/me/orgs':
    get:
      summary: Get all organization of members
      description: This gives the list of all the organization the account user is part of.
      tags:
      - Members
      parameters:
      - name: x-access-token
        in: header
        description: ''
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                - message
                - data
                - metaData
                - error
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Organization list fetched successfully
                  data:
                    type: array
                    items:
                      type: object
                      required:
                      - id
                      - name
                      - description
                      - workspaceId
                      properties:
                        id:
                          type: string
                          example: 0d60ff40-6501-4a05-af5e-bfc9f19896d5
                        name:
                          type: string
                          example: Nthgram
                        description:
                          type: string
                          example: nthgram
                        workspaceId:
                          type: string
                          example: 1R5SDEMR
                  metaData:
                    type: object
                    required:
                    - page
                    - hasMore
                    - pageSize
                    - count
                    properties:
                      page:
                        type: integer
                        example: 1
                      hasMore:
                        type: boolean
                        example: false
                      pageSize:
                        type: integer
                        example: 100
                      count:
                        type: integer
                        example: 5
                  error:
                    type: 'null'
        '404':
          description: Failure
          content:
            application/json:
              schema:
                type: object
                properties: {}

  '{{members-module}}/me/profile':
    get:
      summary: Get profile of current member
      description: Returns basic profile information of the authenticated user.
      tags:
      - Members
      parameters:
      - name: x-access-token
        in: header
        description: Authentication token
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: user-123
                  email:
                    type: string
                    example: user@example.com
                  name:
                    type: string
                    example: John Doe
