name: Frontend Web App Deployment New

on:
  pull_request:
    branches:
    - develop
    types:
    - closed
  workflow_dispatch:


env:
  PROJECT_ID: nthexam-3cb06
  GAR_NAME: sn-development-frontend-app
  GAR_LOCATION: asia-south1
  GAR_SERVICE: dokaai-docs
  SERVICE: dokaai-docs
  REGION: asia-south1
  NODE_VERSION: '20'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: Create .env.production
      run: |
        echo "${{ secrets.WEB_APP_ENV_SECRET_DIESEL }}" > .env.production

    - name: Install, build, and test
      run: |
        pnpm install --frozen-lockfile
        pnpm build
        pnpm test --if-present

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_NTHEXAM_SAK }}'

    - name: Docker Auth
      run: gcloud auth configure-docker "${{ env.GAR_LOCATION }}-docker.pkg.dev"

    - name: Ensure Artifact Registry exists
      run: |
        if ! gcloud artifacts repositories describe "${{ env.GAR_NAME }}" \
          --location="${{ env.GAR_LOCATION }}" \
          --project="${{ env.PROJECT_ID }}" >/dev/null 2>&1; then
          echo "Artifact Registry '${{ env.GAR_NAME }}' does not exist. Creating..."
          gcloud artifacts repositories create "${{ env.GAR_NAME }}" \
            --repository-format=docker \
            --location="${{ env.GAR_LOCATION }}" \
            --description="Docker repository for backend services"
        else
          echo "Artifact Registry '${{ env.GAR_NAME }}' already exists."
        fi    

    - name: Build and Push Container
      run: |
        docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.GAR_SERVICE }}:${{ github.sha }}" -f ./Dockerfile .
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.GAR_SERVICE }}:${{ github.sha }}"

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.GAR_SERVICE }}:${{ github.sha }}"
        env_vars: ${{ secrets.WEB_APP_ENV_SECRET_DIESEL }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
